# Generated by Django 3.0.8 on 2020-08-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.TextField()),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.TextField()),
                ('jamon', models.IntegerField(blank=True, null=True)),
                ('champinon', models.IntegerField(blank=True, null=True)),
                ('pimenton', models.IntegerField(blank=True, null=True)),
                ('dob_queso', models.IntegerField(blank=True, null=True)),
                ('aceitunas', models.IntegerField(blank=True, null=True)),
                ('pepperoni', models.IntegerField(blank=True, null=True)),
                ('salchichon', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pizza',
                'managed': False,
            },
        ),
    ]
